"""Reverse-direction tool: build a `.prompts` file from a generated image.

Reads a PNG's embedded metadata (the same fields written by
`base_generator._save_image_with_metadata`) and emits a `.prompts` file
compatible with `prompts/parser.py`.

Use case: an image was generated, looks good, we want to tweak the
prompt and re-run — without retyping the whole thing. Or recover a
`.prompts` source for an image whose original `.prompts` was discarded.

Run via:
    uv run --project tools/ai_art_generator prompts-from-image <image.png>

Outputs to stdout by default; use -o/--output to write to a file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Tuple

from PIL import Image


# Map the value embedded in PNG `generator` field back to the service
# slug used in `.prompts` headers.
GENERATOR_TO_SERVICE = {
    "OpenAI": "openai",
    "OpenAI GPT-4o": "openai",
    "Google GenAI": "genai",
    "Google": "genai",
    "Gemini": "genai",
}

# Per-service known model prefixes — used to validate that the
# (generator, model) pair we read from PNG metadata is internally
# consistent. Drift between the two suggests stripped/edited metadata.
SERVICE_MODEL_PREFIXES = {
    "openai": ("gpt-image",),
    "genai": ("gemini",),
}


def _infer_service(generator: Optional[str]) -> Optional[str]:
    if not generator:
        return None
    if generator in GENERATOR_TO_SERVICE:
        return GENERATOR_TO_SERVICE[generator]
    lower = generator.lower()
    if "openai" in lower:
        return "openai"
    if "google" in lower or "gemini" in lower:
        return "genai"
    return None


def _validate_service_model(
    service: Optional[str], model: Optional[str]
) -> Optional[str]:
    """Return a warning string if (service, model) look mismatched, else None."""
    if not service or not model:
        return None
    prefixes = SERVICE_MODEL_PREFIXES.get(service)
    if prefixes and not any(model.startswith(p) for p in prefixes):
        return (
            f"PNG metadata mismatch: generator implies service={service!r} "
            f"but model={model!r} doesn't match known prefixes "
            f"{list(prefixes)} — this image's metadata may have been edited."
        )
    return None


def _infer_id(image_path: Path) -> str:
    """Filename stem, normalized — lowercase, spaces/underscores → hyphens."""
    stem = image_path.stem.strip().lower()
    return stem.replace("_", "-").replace(" ", "-")


def build_prompts_file(
    image_path: Path,
    *,
    id_override: Optional[str] = None,
) -> Tuple[str, Optional[str]]:
    """Read PNG metadata from `image_path` and return (prompts_text, warning).

    `warning` is None unless the PNG's service/model fields look mismatched.
    Caller can choose to print the warning to stderr.
    """
    if not image_path.exists():
        raise FileNotFoundError(f"image not found: {image_path}")

    img = Image.open(image_path)
    info = dict(img.info)

    prompt_text = (info.get("prompt") or "").strip()
    if not prompt_text:
        raise ValueError(
            f"no `prompt` field in PNG metadata for {image_path} — "
            f"this image may not have been generated by ai_art_generator, "
            f"or its metadata was stripped."
        )

    description = (info.get("description") or "").strip()
    generator = info.get("generator")
    model = info.get("model")
    size = info.get("size")
    quality = info.get("quality")
    style = info.get("style")

    service = _infer_service(generator)
    warning = _validate_service_model(service, model)

    entry_id = id_override or _infer_id(image_path)
    filename = image_path.name

    # ---- File header ----
    header_lines = ["---"]
    if service:
        header_lines.append(f"service: {service}")
    if model:
        header_lines.append(f"model: {model}")
    if quality:
        header_lines.append(f"quality: {quality}")
    header_lines.append("---")

    # ---- Entry block ----
    title_placeholder = "TODO — short human-readable title"
    description_value = description or "TODO — short description"
    tags_placeholder = "TODO, comma, separated"

    entry_lines = [
        f"=== {entry_id} ===",
        f"filename: {filename}",
        f"title: {title_placeholder}",
        f"description: {description_value}",
        f"tags: {tags_placeholder}",
    ]
    # Per-entry overrides — emit size/style here; quality stays in header.
    if size:
        entry_lines.append(f"size: {size}")
    if style:
        entry_lines.append(f"style: {style}")

    text = (
        "\n".join(header_lines)
        + "\n\n"
        + "\n".join(entry_lines)
        + "\n\n"
        + prompt_text
        + "\n"
    )
    return text, warning


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a .prompts file from a generated image's embedded metadata.",
    )
    parser.add_argument("image", type=Path,
                        help="Path to a PNG with embedded ai_art_generator metadata")
    parser.add_argument("-o", "--output", type=Path, default=None,
                        help="Write to this .prompts path instead of stdout")
    parser.add_argument("--id", default=None,
                        help="Override the inferred entry id (default: filename stem)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite --output if it already exists")
    args = parser.parse_args()

    try:
        text, warning = build_prompts_file(args.image, id_override=args.id)
    except (FileNotFoundError, ValueError) as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    if warning:
        print(f"warning: {warning}", file=sys.stderr)

    if args.output is None:
        sys.stdout.write(text)
        return

    if args.output.exists() and not args.force:
        print(f"error: {args.output} already exists (use --force to overwrite)",
              file=sys.stderr)
        sys.exit(1)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
